[package]
name    = "helm-arch"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
probe = []
instrumentation = ["helm-probe/instrumentation"]

[dependencies]
helm-core.workspace  = true
helm-diag.workspace  = true
helm-probe.workspace = true
log.workspace        = true
thiserror.workspace  = true

[build-dependencies]
helm-decode.workspace = true
