[package]
name    = "helm-arch"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
probe = ["dep:helm-probe"]

[dependencies]
helm-core.workspace  = true
helm-diag.workspace  = true
helm-probe           = { workspace = true, optional = true }
log.workspace        = true
thiserror.workspace  = true
