[package]
name    = "helm-jit"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
helm-core.workspace   = true
helm-arch.workspace   = true
helm-memory.workspace = true
dynasm   = { version = "2", optional = true }
dynasmrt = { version = "2", optional = true }
libc     = { workspace = true }
log      = { workspace = true }

[features]
default = ["backend-dynasm"]
backend-dynasm = ["dep:dynasm", "dep:dynasmrt"]
