[package]
name    = "helm-jit"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
helm-core.workspace   = true
helm-arch.workspace   = true
helm-memory.workspace = true
helm-stats.workspace  = true
dynasm   = { version = "2", optional = true }
dynasmrt = { version = "2", optional = true }
libc     = { workspace = true }
log      = { workspace = true }

[build-dependencies]
cc     = { version = "1", optional = true }
object = { version = "0.36", optional = true }

[features]
default = ["backend-dynasm"]
backend-dynasm  = ["dep:dynasm", "dep:dynasmrt"]
backend-stencil = ["dep:cc", "dep:object"]
