[package]
name    = "helm-platform"
version.workspace = true
edition.workspace = true
description = "Platform definitions, device topology, and runtime device attachment"

[lints]
workspace = true

[dependencies]
helm-arch.workspace = true
helm-devices.workspace = true
helm-hw-char.workspace = true
helm-hw-intc.workspace = true
helm-hw-pci.workspace = true
helm-hw-rtc.workspace = true
helm-memory.workspace = true
thiserror.workspace = true
