//! Auto-generated RISC-V decoders from `.decode` files via `build.rs`.
//!
//! Each `include!` pulls in a `pub(crate) fn decode_<ext>(insn: u32) -> &'static str`
//! generated by `helm-decode`'s code-generation pipeline.
//!
//! The generated functions return the instruction mnemonic string on match,
//! or `"UNKNOWN"` for no match.

// Base ISA
include!(concat!(env!("OUT_DIR"), "/riscv64_base.rs"));

// Standard extensions
include!(concat!(env!("OUT_DIR"), "/riscv64_m.rs"));
include!(concat!(env!("OUT_DIR"), "/riscv64_a.rs"));
include!(concat!(env!("OUT_DIR"), "/riscv64_f.rs"));
include!(concat!(env!("OUT_DIR"), "/riscv64_zicsr.rs"));

// Bit-manipulation
include!(concat!(env!("OUT_DIR"), "/riscv64_zb.rs"));

// Vector
include!(concat!(env!("OUT_DIR"), "/riscv64_v.rs"));
include!(concat!(env!("OUT_DIR"), "/riscv64_zvk.rs"));

// Vendor
include!(concat!(env!("OUT_DIR"), "/riscv64_xthead.rs"));

/// Decode an instruction word using all generated extension decoders in priority order.
///
/// Returns the mnemonic string (e.g. `"ADD"`, `"VADD_VV"`) or `"UNKNOWN"`.
///
/// Priority: base → M → A → F → Zicsr → Zb → V → Zvk → XThead
#[allow(dead_code)]
pub(crate) fn decode_generated(insn: u32) -> &'static str {
    macro_rules! try_ext {
        ($fn:ident) => {{
            let m = $fn(insn);
            if m != "UNKNOWN" {
                return m;
            }
        }};
    }

    try_ext!(decode_riscv64_base);
    try_ext!(decode_riscv64_m);
    try_ext!(decode_riscv64_a);
    try_ext!(decode_riscv64_f);
    try_ext!(decode_riscv64_zicsr);
    try_ext!(decode_riscv64_zb);
    try_ext!(decode_riscv64_v);
    try_ext!(decode_riscv64_zvk);
    try_ext!(decode_riscv64_xthead);

    "UNKNOWN"
}
