[package]
name    = "helm-debug"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = []
instrumentation = ["helm-probe/instrumentation"]

[dependencies]
helm-core.workspace  = true
helm-diag.workspace  = true
helm-probe.workspace = true
thiserror.workspace  = true
log.workspace        = true
