[package]
name    = "helm-hw-intc"
version.workspace = true
edition.workspace = true
description = "Interrupt controllers (GICv2 and GICv3)"

[lints]
workspace = true

[dependencies]
helm-devices.workspace = true
helm-diag.workspace   = true
helm-stats.workspace  = true
log.workspace = true
helm-probe = { workspace = true, optional = true }

[features]
probe = ["dep:helm-probe"]
