[package]
name    = "helm-engine"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
helm-core.workspace    = true
helm-probe.workspace   = true
helm-arch.workspace    = true
helm-diag.workspace    = true
helm-event.workspace   = true
helm-stats.workspace   = true
helm-timing.workspace  = true
helm-memory.workspace  = true
helm-devices.workspace = true
helm-hw-char.workspace = true
helm-hw-rtc.workspace = true
helm-hw-intc = { workspace = true, features = ["probe"] }
helm-debug.workspace   = true
helm-plugin.workspace  = true
helm-platform.workspace = true
libc.workspace         = true
thiserror.workspace    = true
log.workspace          = true
flate2                = "1"
helm-jit              = { workspace = true, optional = true }

[features]
jit = ["dep:helm-jit"]
jit-dynasm = ["jit", "helm-jit/backend-dynasm"]
jit-stencil = ["jit", "helm-jit/backend-stencil"]

[dev-dependencies]
helm-hw-timer.workspace = true
