[package]
name    = "helm-hw-virtio"
version.workspace = true
edition.workspace = true
description = "VirtIO MMIO transport, backend trait, and feature bit constants"

[lints]
workspace = true

[dependencies]
helm-devices.workspace = true
helm-core.workspace = true
helm-diag.workspace = true
helm-hw-pci.workspace = true
log.workspace = true

[dev-dependencies]
helm-memory.workspace = true
